spring.application.name=KamalCart

# Database Configuration (use .env overrides if present)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.show-sql=true
management.security.enabled=false
spring.web.resources.static-locations=file:uploads/
